version: '1'
services:
  redis:
    image: "redis:latest"
    container_name: box-redis
    ports:
      - "6379:6379"
  mysql:
    image: "mysql:latest"
    container_name: box-redis
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #root管理员用户密码
      MYSQL_DATABASE: box
    ports:
      - "3306:3306"
  minio:
    image: "minio/minio:latest"
    volumes:
      - /home/data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: JvUphxqQL9Eur7ExXurC
      MINIO_SECRET_KEY: rsFR657sUjRm6DQoVUYk3EfTue9BdDCxB7kD4tffku8DeviKgcFbNoLCMMc2Ez7D